version: '3'
services:
    transmission:
        build: .
        container_name: transmission
        # PUID and PGID should be the user that has access to the volumes mentioned below 
        environment: 
          - PUID=1001
          - PGID=1001
        ports:
          - "9091:9091"
          - "51617:51617"
          - "51617:51617/udp"
        volumes:
          - /home/torrent/config:/config
          - /home/torrent/downloads:/downloads
        restart: always
