version: '3'
services:
    teamspeak:
        build: .
        container_name: transmission
        environment: 
          - PUID=1001
          - PGID=1001
        ports:
          - "9091:9091"
          - "51413:51413"
          - "51413:51413/udp"
        volumes:
          - /home/torrent/config:/config
          - /home/torrent/downloads:/downloads
        restart: always
